### ISSUE TITLE
Well perforation issue : Invalid mapping

### ISSUE THREAD

**Issue by margauxraguenel** [GEOSX/GEOS#2227]
**Describe the bug**
I'm trying to launch GEOSX on a real application case with one well. 
As preprocessing, I have checked all the cells concerned by the well and compute the cell centers: 
![image](https://user-images.githubusercontent.com/32702400/208930097-8061b391-3eeb-4c5f-a5c9-5a081d4a74e7.png)
These coordinates are used in the xml definition and well interpreted by GEOSX for the perforation coordinates:
![image](https://user-images.githubusercontent.com/32702400/208929869-b9b875f1-9a69-43d0-8813-7a39d7a0f475.png)

However, I got the following error:
![image](https://user-images.githubusercontent.com/32702400/208930511-103ce6b8-7d3e-4ec6-a62f-8721e1874552.png)

Additional information: 
No issue in sequential. 

**Platform (please complete the following information):**
- Machine P2
- Compiler: gcc 8.3.0
- GEOSX Version 88f9773

**Additional context**
Solution proposed in Issue #2205 does not work, a more recent version of GEOSX has been used.

@jeannepellerin 

duplicate issue #2256

**Comment by dkachuma** [comment]
I have recreated the situation in the attached model 
[issue2227.tar.gz](https://github.com/GEOSX/GEOSX/files/10421877/issue2227.tar.gz). The mesh in this model is a single element vtu in which the single element is a pyramid with all 5 points having $z>0$. There is a well with a single segment whose element centre is well below 0 at $z=-105$. As such I would expect GEOSX to fail to find the intersection of this well with the mesh and issue an error. However, GEOSX runs fine and attaches the well to the single element.

This is because the pyramid has a base whose points are not coplanar. As such, in `computationalGeometry::isPointInsidePolyhedron`, the 5 face centres are calculated as
```
(-66.7,   0.0, 60.0)
(  0.0,  66.7, 60.0)
(  0.0, -66.7, 60.0)
( 66.7,   0.0, 60.0)
(  0.0,   0.0, 53.3)
```
while the element centre is `(0.0, 0.0, 52.0)`. That is, all face centres are above the element centre. As such, the computation fails to determine that the point `(0.0, 0.0, -105.0)` is actually outside the element.

**Comment by untereiner** [comment]
I think the normal computed in `centroid_3DPolygon` of `ComputationalGeometry.hpp` is wrong.
The newell's method for computing the plane equation of a polygon is a sum modulo the indices of the vertices of the face. I think the existing function misses the last triangle of the polygon.

**Comment by dkachuma** [comment]
I can confirm that the branch `feature/untereiner/newell_normal` fixes this issue. The change to the face centre calculation ensures that the cell face centres are on either side of the element centre.

**Comment by untereiner** [comment]
My first comment moved somewhere in the limbes... Ok I was thinking that the function `centroid_3DPolygon` in `computationalGeometry.hpp` is wrong. I implemented the newell's method for polygonal normal approximation. I can also had a special case for degree 3 faces.
