### ISSUE TITLE
What‘s "netToGross" for?

### ISSUE THREAD

**Issue by FishYNY** [GEOSX/GEOS#2340]
I recently noticed a parameter "netToGross". It is imported from mesh data but is never called. So I'm wondering what is "netToGross" for. Besides, what's the difference between "ptscotch" and "parmetis".

  <Mesh>

    <VTKMesh
      name="mesh"
      logLevel="5"
      partitionMethod="ptscotch"
      scale="{ 50, 50, 50 }"
      fieldsToImport="{ PORO, NTG, DENSITY, BULKMOD }"
      fieldNamesInGEOSX="{ rockPorosity_referencePorosity, netToGross, skeleton_density, skeleton_bulkModulus }"
      file="pebi3d_with_properties.vtu"/>

  </Mesh>

**Comment by francoishamon** [comment]
Hello @FishYNY,

The net to gross is a scaling factor for the porosity and horizontal permeability. It is used by the flow solvers, for instance here: https://github.com/GEOSX/GEOSX/blob/5841bf7f79a90368e19e399199891d73fe20ad78/src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp#L354-L355

The main reason to have this in the code is to be able to easily compare with industrial reservoir simulation decks which typically have this scaling parameter. So, unless you are trying to match your GEOSX results with another simulation deck that uses net-to-gross, I would advise you not to use it and just let GEOSX initialize it to its default value of 1.

Parmetis and ptscotch refer to the algorithm that partition the mesh (= cut it into small subdomains processed by separate MPI processes during the simulation). In large-scale simulations with many MPI processes, you want to have well-balanced partitions to achieve a good performance. In my very limited experience, I have observed that `ptscotch` produces more balanced partitions than `parmetis`, but this is probably case-specific.

If you use `parmetis`, don't forget to set the `partitionRefinement` keyword to a large number (say, '20'), because this will improve the quality of the partitions quite significantly.

**Comment by FishYNY** [comment]
@francoishamon Thanks a lot. You are so kind and nice to answer my questions in detail.
